# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Practicing the Presence"  # Title of the link.
  url = "spiritualdirection/"  # Widget Page folder name.
  weight = 10  # Position of the link in the navigation bar.
  identifier = "SD"

[[main]]
  name = "Spiritual Direction"  # Title of the link.
  url = "spiritualdirection#what"  # Widget Page folder name.
  weight = 11  # Position of the link in the navigation bar.
  parent = "SD"

[[main]]
  name = "Messages"  # Title of the link.
  url = "messages/"  # Widget Page folder name.
  weight = 12  # Position of the link in the navigation bar.
  parent = "SD"

[[main]]
  name = "Pricing and Payments"  # Title of the link.
  url = "spiritualdirection#pricing"  # Widget Page folder name.
  weight = 13  # Position of the link in the navigation bar.
  parent = "SD"

[[main]]
  name = "About Brice"  # Title of the link.
  url = "aboutbrice/"  # Widget Page folder name.
  weight = 20  # Position of the link in the navigation bar.

[[main]]
  name = "Contact"  # Title of the link.
  url = "contact/"  # Widget Page folder name.
  weight = 30  # Position of the link in the navigation bar.

